"""empty message

Revision ID: 3136ad60d2f8
Revises: 47808d54df4b
Create Date: 2024-11-27 21:55:21.661585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3136ad60d2f8'
down_revision: Union[str, None] = '47808d54df4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'confirmed', 'canceled', name='status').create(op.get_bind())
    sa.Enum('economy', 'compact', 'luxury', name='category').create(op.get_bind())
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'canceled', name='status', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cars', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('economy', 'compact', 'luxury', name='category'),
               existing_nullable=False,
               postgresql_using='category::category')
    op.create_foreign_key(None, 'cars', 'locations', ['locatioon_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.alter_column('cars', 'category',
               existing_type=sa.Enum('economy', 'compact', 'luxury', name='category'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('reviews')
    op.drop_table('bookings')
    op.drop_table('locations')
    sa.Enum('economy', 'compact', 'luxury', name='category').drop(op.get_bind())
    sa.Enum('pending', 'confirmed', 'canceled', name='status').drop(op.get_bind())
    # ### end Alembic commands ###
