"""Remove address column from location model

Revision ID: 718b0f5f482d
Revises: dfd0b3928747
Create Date: 2024-12-04 21:14:58.239358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718b0f5f482d'
down_revision: Union[str, None] = 'dfd0b3928747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
